- name: Terminate tagged instances
  hosts: tag_{{ tag_name }}_{{ tag_value }}
  tasks:
    - ec2_facts:
    - ec2:
        state: absent
        region: "{{ ansible_ec2_placement_region }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
      delegate_to: localhost
